### ISSUE TITLE
wrap the book tittles a bit better

### ISSUE THREAD

**Issue by rski** [barrucadu/bookdb#9]
Because of one really long book tittle, there is a lot of wasted space in the Title column, so I end up having to scroll left and right a lot for no real reason
![2015-11-21-200605_803x331_escrotum](https://cloud.githubusercontent.com/assets/2960312/11319772/4e4fb1e4-908b-11e5-8389-34043eeb977d.png)

**Comment by barrucadu** [comment]
I don't get scrolling, at least when I use it fullscreen, but I do get an annoying wrapping of last read dates. So I've set a max width per table cell of 500px in 0da071d.
